version: "3.3"
services:
  openlist:
    build:
      context: .
      dockerfile: Dockerfile
    image: "ghcr.io/openlistteam/openlist:latest"
    container_name: openlist
    hostname: openlist
    restart: always
    volumes:
      - ${CONFIG_PATH:-/etc/openlist}:/opt/openlist/data
    ports:
      - ${OPENLIST_PORT-:5244}:5244
      - ${OPENLIST_PORT_SSL-:5245}:5245
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${OPENLIST_UID:-0}
      - PGID=${OPENLIST_GID:-0}
      - UMASK=${OPENLIST_UMASK:-022}
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite3}
      - DATABASE_HOST=${DATABASE_HOST:-""}
      - DATABASE_PORT=${DATABASE_PORT:-0}
      - DATABASE_NAME=${DATABASE_NAME:-""}
      - DATABASE_USER=${DATABASE_USER:-""}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-""}
