name: "错误报告"
description: 错误报告 / 问题
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告，请**务必确认您的issue不是重复的且不是因为您的操作或版本问题**

  - type: checkboxes
    attributes:
      label: 请确认以下事项
      description: |
        您必须勾选以下所有内容，否则您的issue可能会被直接关闭。或者您可以去[讨论区](https://github.com/OpenListTeam/OpenList/discussions)
      options:
        - label: |
            我已经阅读了[文档](https://docs.oplist.org)。
        - label: |
            我确定没有重复的issue或讨论。
        - label: |
            我确定是`OpenList`的问题，而不是其他原因（例如[网络](https://docs.oplist.org/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。
        - label: |
            我确定这个问题在最新版本中没有被修复。

  - type: input
    id: version
    attributes:
      label: OpenList 版本
      description: |
        您使用的是哪个版本的软件？请不要使用`latest`或`master`作为答案。
      placeholder: v4.xx.xx
    validations:
      required: true
  - type: input
    id: driver
    attributes:
      label: 使用的存储驱动
      description: |
        您使用的是哪个存储驱动？
      placeholder: "例如: Onedrive"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 复现链接
      description: |
        请提供能复现此问题的链接，请知悉如果不提供它你的issue可能会被直接关闭
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: 配置
      description: |
        请提供您的`OpenList`应用的配置文件，并截图相关存储配置。(可隐藏隐私字段)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: |
        请复制粘贴错误日志，或者截图
