name: "Feature Request"
description: Feature Request
title: "[Feature] "
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Please make sure of the following things
      description: You may select more than one, even select all.
      options:
        - label: I have read the [documentation](https://docs.openlist.org).
        - label: I'm sure there are no duplicate issues or discussions.
        - label: I'm sure this feature is not implemented.
        - label: I'm sure it's a reasonable and popular requirement.
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: |
        Solutions to achieve this requirement.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Any other context or screenshots about the feature request here, or information you find helpful.
