name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up environment
        run: |
          WEB_VERSION=$(curl -sSL "https://api.github.com/repos/OpenListTeam/OpenList-Frontend/releases/latest" | jq -r '.tag_name')
          echo "WEB_VERSION=${WEB_VERSION}" >> $GITHUB_ENV
          echo "GHCR_IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "GHCR_IMAGE_TAG=${GITHUB_REF_NAME,,}" >> $GITHUB_ENV
          wget -qO- "https://github.com/OpenListTeam/OpenList-Frontend/releases/download/${WEB_VERSION}/openlist-frontend-dist-${WEB_VERSION}.tar.gz" | tar xz -C public/dist

      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          tags: |
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ env.GHCR_IMAGE_TAG }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest

  release_android:
    name: Release - Android
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: stable

      - name: Build Android
        run: |
          bash build.sh release android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/compress/*
